package alltogether;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class MailClient {

	public static void sendMail(String addresses, String project, String state) {
		final String username = PropertyReader.getString("MailClient.username"); //$NON-NLS-1$
		final String password = PropertyReader.getString("MailClient.password"); //$NON-NLS-1$

		Properties props = new Properties();
		props.put("mail.smtp.auth", PropertyReader.getString("MailClient.smtpauth")); //$NON-NLS-1$ //$NON-NLS-2$
		props.put("mail.smtp.starttls.enable", PropertyReader.getString("MailClient.smtpstarttlsenable")); //$NON-NLS-1$ //$NON-NLS-2$
		props.put("mail.smtp.host", PropertyReader.getString("MailClient.smtphost")); //$NON-NLS-1$ //$NON-NLS-2$
		props.put("mail.smtp.port", PropertyReader.getString("MailClient.smtpport")); //$NON-NLS-1$ //$NON-NLS-2$

		Session session = Session.getInstance(props,
				new javax.mail.Authenticator() {
					protected PasswordAuthentication getPasswordAuthentication() {
						return new PasswordAuthentication(username, password);
					}
				});

		try {
			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress(username));
			String[] toAddresses = addresses.split("\\|"); //$NON-NLS-1$
			for (String toAddress : toAddresses) {
				message.addRecipient(Message.RecipientType.TO,
						new InternetAddress(toAddress));
			}
			message.setSubject("Project : "+ project +" is in "+ state +" state"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
			DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd"); //$NON-NLS-1$
			Date date = new Date();
			System.out.println(dateFormat.format(date));
			String content = "Project : " //$NON-NLS-1$
					+ project
					+ " is in " //$NON-NLS-1$
					+ state
					+ " state. \n\nThis is an autogenerated notification mail."; //$NON-NLS-1$

			message.setText(content);

			Transport.send(message);
			System.out.println("Mail sent"); //$NON-NLS-1$

		} catch (MessagingException e) {
			e.printStackTrace();
		}
	}
}
